<a href="https://colab.research.google.com/github/nadamohamed-10/DEPI-s-graduation-project/blob/phase1_update/Depi_Graduation_Project_Cleaning_Phase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drivee')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
print(os.listdir('/content/drive/MyDrive'))

['Document from Mariam Fouda.pdf', 'CV Fatma.pdf', 'Colab Notebooks', 'Untitled video.gvid', 'Vids Exports', 'CV.pdf', 'Untitled Diagram', 'SRS.sdr', 'Portfolio (1).pdf', 'supermarket_sales - Sheet1.csv', 'Portfolio.pdf', 'Big Data Task.zip', 'US_Accidents_March23.csv']

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/US_Accidents_March23.csv",
    nrows=100000
)

df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [ ]:
df = df.drop(columns=[
    "Description",
    "ID",
    "Source",
    "Zipcode",
    "Timezone",
    "Country",
    "Astronomical_Twilight",
    "Nautical_Twilight",
    "Civil_Twilight",
    "End_Lat",
    "End_Lng",
    "Turning_Loop"
], errors='ignore')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 35 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Severity           100000 non-null  int64
 1   Start_Time         100000 non-null  object
 2   End_Time           100000 non-null  object
 3   Start_Lat          100000 non-null  float64
 4   Start_Lng          100000 non-null  float64
 5   Distance(mi)       100000 non-null  float64
 6   Street             100000 non-null  object
 7   City               99999 non-null   object
 8   County             100000 non-null  object
 9   State              100000 non-null  object
 10  Airport_Code       99993 non-null   object
 11  Weather_Timestamp  98946 non-null   object
 12  Temperature(F)     98409 non-null   float64
 13  Wind_Chill(F)      4322 non-null    float64
 14  Humidity(%)        98144 non-null   float64
 15  Pressure(in)       98708 non-null   float64
 16  Visibility(mi)     98154 non-null   float64
 17  Wind_Direction     98936 non-null   object
 18  Wind_Speed(mph)    76180 non-null   float64
 19  Precipitation(in)  7368 non-null    float64
 20  Weather_Condition  98396 non-null   object
 21  Amenity            100000 non-null  bool
 22  Bump               100000 non-null  bool
 23  Crossing           100000 non-null  bool
 24  Give_Way           100000 non-null  bool
 25  Junction           100000 non-null  bool
 26  No_Exit            100000 non-null  bool
 27  Railway            100000 non-null  bool
 28  Roundabout         100000 non-null  bool
 29  Station            100000 non-null  bool
 30  Stop               100000 non-null  bool
 31  Traffic_Calming    100000 non-null  bool
 32  Traffic_Signal     100000 non-null  bool
 33  Turning_Loop       100000 non-null  bool
 34  Sunrise_Sunset     99999 non-null   object
dtypes: bool(13), float64(10), int64(1), object(11)
memory usage: 18.0+ MB

In [ ]:
#convert datatype of End_Time & Start_Time into datetime
df['Start_Time'] = pd.to_datetime(df['Start_Time'])
df['End_Time'] = pd.to_datetime(df['End_Time'])

In [ ]:
df['start_year'] = df['Start_Time'].dt.year
df['start_month'] = df['Start_Time'].dt.month
df['start_day'] = df['Start_Time'].dt.day
df['start_hour'] = df['Start_Time'].dt.hour

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 39 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Severity           100000 non-null  int64
 1   Start_Time         100000 non-null  datetime64[ns]
 2   End_Time           100000 non-null  datetime64[ns]
 3   Start_Lat          100000 non-null  float64
 4   Start_Lng          100000 non-null  float64
 5   Distance(mi)       100000 non-null  float64
 6   Street             100000 non-null  object
 7   City               99999 non-null   object
 8   County             100000 non-null  object
 9   State              100000 non-null  object
 10  Airport_Code       99993 non-null   object
 11  Weather_Timestamp  98946 non-null   object
 12  Temperature(F)     98409 non-null   float64
 13  Wind_Chill(F)      4322 non-null    float64
 14  Humidity(%)        98144 non-null   float64
 15  Pressure(in)       98708 non-null   float64
 16  Visibility(mi)     98154 non-null   float64
 17  Wind_Direction     98936 non-null   object
 18  Wind_Speed(mph)    76180 non-null   float64
 19  Precipitation(in)  7368 non-null    float64
 20  Weather_Condition  98396 non-null   object
 21  Amenity            100000 non-null  bool
 22  Bump               100000 non-null  bool
 23  Crossing           100000 non-null  bool
 24  Give_Way           100000 non-null  bool
 25  Junction           100000 non-null  bool
 26  No_Exit            100000 non-null  bool
 27  Railway            100000 non-null  bool
 28  Roundabout         100000 non-null  bool
 29  Station            100000 non-null  bool
 30  Stop               100000 non-null  bool
 31  Traffic_Calming    100000 non-null  bool
 32  Traffic_Signal     100000 non-null  bool
 33  Turning_Loop       100000 non-null  bool
 34  Sunrise_Sunset     99999 non-null   object
 35  start_year         100000 non-null  int32
 36  start_month        100000 non-null  int32
 37  start_day          100000 non-null  int32
 38  start_hour         100000 non-null  int32
dtypes: bool(13), datetime64[ns](2), float64(10), int32(4), int64(1), object(9)
memory usage: 19.6+ MB

In [ ]:
df.isnull().sum()

Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
Distance(mi)             0
Street                   0
City                     1
County                   0
State                    0
Airport_Code             7
Weather_Timestamp     1054
Temperature(F)        1591
Wind_Chill(F)        95678
Humidity(%)           1856
Pressure(in)          1292
Visibility(mi)        1846
Wind_Direction        1064
Wind_Speed(mph)      23820
Precipitation(in)    92632
Weather_Condition     1604
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Sunrise_Sunset           1
start_year               0
start_month              0
start_day                0
start_hour               0
dtype: int64

In [ ]:
#for num cols use median to fill missing and median better than mean (sensitive with outliers)
num_cols = [
    'Temperature(F)',
    'Humidity(%)',
    'Pressure(in)',
    'Visibility(mi)',
    'Wind_Speed(mph)',
    'Wind_Chill(F)'
]

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

# precipitation usually = 0 when missing
df['Precipitation(in)'].fillna(0, inplace=True)

/tmp/ipykernel_19011/699912482.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_19011/699912482.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Precipitation(in)'].fillna(0, inplace=True)

In [ ]:
#for categorical cols use mode ,assume that the missing was the most frequent data
cat_cols = [
    'Weather_Condition',
    'Wind_Direction',
    'Sunrise_Sunset',
    'City'
]
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_19011/400052857.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [ ]:
#drop 1 missing
#df.dropna(subset=['City'], inplace=True)

In [ ]:
df.isnull().sum()

Severity                0
Start_Time              0
End_Time                0
Start_Lat               0
Start_Lng               0
Distance(mi)            0
Street                  0
City                    0
County                  0
State                   0
Airport_Code            7
Weather_Timestamp    1054
Temperature(F)          0
Wind_Chill(F)           0
Humidity(%)             0
Pressure(in)            0
Visibility(mi)          0
Wind_Direction          0
Wind_Speed(mph)         0
Precipitation(in)       0
Weather_Condition       0
Amenity                 0
Bump                    0
Crossing                0
Give_Way                0
Junction                0
No_Exit                 0
Railway                 0
Roundabout              0
Station                 0
Stop                    0
Traffic_Calming         0
Traffic_Signal          0
Turning_Loop            0
Sunrise_Sunset          0
start_year              0
start_month             0
start_day               0
start_hour              0
dtype: int64

In [ ]:
print("Unique values per column:")
for col in df.columns:
    print(f"\n{col}:")
    print(df[col].unique())

Unique values per column:

Severity:
[3 2 1 4]

Start_Time:
<DatetimeArray>
['2016-02-08 05:46:00', '2016-02-08 06:07:59', '2016-02-08 06:49:27',
 '2016-02-08 07:23:34', '2016-02-08 07:39:07', '2016-02-08 07:44:26',
 '2016-02-08 07:59:35', '2016-02-08 07:59:58', '2016-02-08 08:00:40',
 '2016-02-08 08:10:04',
 ...
 '2016-04-05 15:15:50', '2016-04-05 15:28:56', '2016-04-05 15:45:49',
 '2016-04-05 15:47:30', '2016-04-05 15:48:40', '2016-04-05 15:52:14',
 '2016-04-05 15:57:10', '2016-04-05 16:02:16', '2016-04-05 16:01:17',
 '2016-04-05 16:06:41']
Length: 98896, dtype: datetime64[ns]

End_Time:
<DatetimeArray>
['2016-02-08 11:00:00', '2016-02-08 06:37:59', '2016-02-08 07:19:27',
 '2016-02-08 07:53:34', '2016-02-08 08:09:07', '2016-02-08 08:14:26',
 '2016-02-08 08:29:35', '2016-02-08 08:29:58', '2016-02-08 08:30:40',
 '2016-02-08 08:40:04',
 ...
 '2016-04-05 16:15:50', '2016-04-05 16:28:56', '2016-04-05 16:45:49',
 '2016-04-05 16:47:30', '2016-04-05 16:48:40', '2016-04-05 16:52:14',
 '2016-04-05 16:57:10', '2016-04-05 17:02:16', '2016-04-05 17:01:17',
 '2016-04-05 17:06:41']
Length: 96724, dtype: datetime64[ns]

Start_Lat:
[39.865147 39.928059 39.063148 ... 33.849846 34.121517 33.995079]

Start_Lng:
[ -84.058723  -82.831184  -84.032608 ... -117.536896 -117.361183
 -118.013443]

Distance(mi):
[1.000e-02 0.000e+00 1.320e+00 1.090e+00 1.280e+00 4.800e-01 1.670e+00
 9.400e-01 2.790e+00 7.100e-01 2.040e+00 1.650e+00 1.730e+00 7.070e+00
 5.150e+00 1.193e+01 7.800e-01 7.780e+00 2.650e+00 1.080e+00 1.218e+01
 1.300e-01 9.800e-01 1.408e+01 4.110e+00 8.250e+00 1.088e+01 2.404e+01
 1.040e+00 5.700e-01 9.860e+00 6.000e-01 6.700e-01 7.000e-01 2.580e+00
 1.360e+00 6.100e-01 3.300e-01 5.900e-01 7.300e-01 1.820e+00 1.390e+00
 2.630e+00 1.100e+00 3.540e+00 4.950e+00 2.530e+00 1.300e+00 2.100e+00
 4.400e-01 1.910e+00 1.030e+00 1.350e+00 6.300e-01 1.980e+00 9.000e-01
 1.170e+00 9.660e+00 8.000e-02 2.500e-01 9.220e+00 1.380e+00 1.700e+00
 7.900e-01 1.440e+00 1.450e+00 7.200e-01 1.000e+00 1.940e+00 9.960e+00
 1.490e+00 1.100e-01 4.910e+00 6.900e-01 1.720e+00 1.510e+00 1.520e+00
 1.660e+00 2.770e+00 5.300e-01 4.160e+00 4.580e+00 1.840e+00 1.110e+00
 9.200e-01 2.120e+00 2.140e+00 6.220e+00 1.020e+00 5.690e+00 4.790e+00
 6.200e-01 2.280e+00 1.317e+01 1.430e+00 1.640e+00 2.420e+00 1.130e+00
 4.500e-01 6.500e-01 1.540e+00 2.000e+00 2.300e-01 2.380e+00 3.440e+00
 8.160e+00 1.600e-01 7.930e+00 1.150e+00 1.700e-01 2.800e-01 5.000e-02
 1.600e+00 1.590e+00 5.860e+00 8.000e-01 2.163e+01 9.750e+00 1.114e+01
 1.010e+00 2.400e-01 2.760e+00 2.600e-01 7.000e-02 7.880e+00 1.185e+01
 5.113e+01 5.000e-01 2.750e+00 7.400e-01 3.310e+00 2.470e+00 3.420e+00
 5.200e-01 4.600e-01 6.490e+00 2.000e-02 1.070e+00 1.900e-01 1.870e+00
 1.000e-01 9.000e-02 8.900e-01 2.900e-01 3.350e+00 7.500e-01 3.000e-02
 3.920e+00 1.780e+00 1.680e+00 2.200e-01 2.570e+00 3.590e+00 9.900e-01
 3.400e-01 7.050e+00 1.410e+00 6.630e+00 1.400e-01 7.700e-01 3.050e+00
 7.060e+00 9.500e-01 4.700e-01 3.200e-01 1.880e+00 9.270e+00 1.200e-01
 3.030e+00 3.600e-01 6.590e+00 4.710e+00 5.770e+00 7.600e-01 1.190e+00
 1.920e+00 4.100e-01 2.180e+00 2.540e+00 1.230e+00 9.600e-01 1.330e+00]

Street:
['I-70 E' 'Brice Rd' 'State Route 32' ... 'Pardall Rd' 'E Blue Star St'
 'Ankerton St']

City:
['Dayton' 'Reynoldsburg' 'Williamsburg' 'Westerville' 'Columbus'
 'Miamisburg' 'Johnstown' 'Dublin' 'Canal Winchester' 'Lebanon' 'Sabina'
 'Goshen' 'Waynesville' 'Springboro' 'Carroll' 'Oregonia' 'Independence'
 'Maple Heights' 'Grove City' 'Findlay' 'Fairborn' 'Piqua' 'New Richmond'
 'Batavia' 'Galena' 'Barberton' 'Akron' 'Mansfield' 'Cleveland' 'Bethel'
 'Pataskala' 'Seville' 'Bellville' 'Troy' 'Wilmington' 'North Olmsted'
 'Groveport' 'Orient' 'Tiro' 'Strongsville' 'Beavercreek' 'Circleville'
 'Peebles' 'Hurricane' 'Xenia' 'Elyria' 'Pickerington' 'Burbank'
 'Zanesville' 'North Baltimore' 'Mount Sterling' 'Tipp City' 'Moraine'
 'Hilliard' 'Bowling Green' 'Maineville' 'Vermilion' 'Milford' 'Brookpark'
 'Fraziers Bottom' 'Cambridge' 'Delaware' 'Moscow' 'Oberlin' 'Sardinia'
 'Lewis Center' 'Urbancrest' 'Brecksville' 'Frankfort' 'Blanchester'
 'Casstown' 'Lima' 'Amelia' 'Newark' 'Springfield' 'Vandalia' 'Galloway'
 'Bloomingburg' 'Gallipolis' 'Lockbourne' 'Milan' 'Mason' 'Millersport'
 'New Carlisle' 'Sunbury' 'Owensville' 'London' 'Vallejo' 'Hayward'
 'Walnut Creek' 'Cupertino' 'San Jose' 'Pleasanton' 'San Francisco'
 'Orinda' 'Livermore' 'Cotati' 'Concord' 'Sunnyvale' 'Sacramento'
 'Oakland' 'Alviso' 'Morgan Hill' 'Petaluma' 'Martinez' 'Millbrae'
 'North Highlands' 'Windsor' 'Alamo' 'San Martin' 'Healdsburg' 'Brisbane'
 'Palo Alto' 'Milpitas' 'Davis' 'Elk Grove' 'Half Moon Bay' 'Menlo Park'
 'Tracy' 'Carmichael' 'Granite Bay' 'Union City' 'Pleasant Hill'
 'San Mateo' 'Rancho Cordova' 'Nevada City' 'Vacaville' 'Roseville'
 'Isleton' 'Lincoln' 'El Dorado' 'Corte Madera' 'San Leandro' 'Danville'
 'Los Gatos' 'Castro Valley' 'Stockton' 'Willits' 'Santa Rosa' 'Los Altos'
 'Richmond' 'Dixon' 'Nice' 'Antioch' 'Angwin' 'Novato' 'Burlingame'
 'Sunol' 'Placerville' 'Fairfield' 'Scotts Valley' 'Linden' 'Santa Clara'
 'San Pablo' 'Pinole' 'Redwood City' 'Salinas' 'Soquel' 'Monterey'
 'Fremont' 'Hercules' 'Seaside' 'Saratoga' 'American Canyon' 'Wilton'
 'Pittsburg' 'Grass Valley' 'Santa Cruz' 'Lodi' 'Sonoma' 'Auburn'
 'Orangevale' 'Emeryville' 'South San Francisco' 'Lathrop' 'Cameron Park'
 'San Bruno' 'Modesto' 'Berkeley' 'Gilroy' 'Escalon' 'Byron' 'Penryn'
 'Citrus Heights' 'El Dorado Hills' 'El Cerrito' 'Suisun City' 'Fair Oaks'
 'Napa' 'Colfax' 'Rocklin' 'Mather' 'Mill Valley' 'San Carlos' 'Aptos'
 'San Ramon' 'Woodland' 'Loomis' 'Folsom' 'Walnut Grove' 'Rodeo'
 'San Lorenzo' 'Sausalito' 'Portola Valley' 'Pope Valley' 'Manteca'
 'Daly City' 'Mokelumne Hill' 'Occidental' 'Newcastle' 'Guerneville'
 'Calistoga' 'Galt' 'Crockett' 'Glen Ellen' 'Rohnert Park' 'Jackson'
 'Ripon' 'Lafayette' 'Fulton' 'Sebastopol' 'San Quentin' 'Forestville'
 'Hollister' 'West Sacramento' 'Angels Camp' 'Acampo' 'Valley Springs'
 'Delhi' 'Shingle Springs' 'Ione' 'Yountville' 'French Camp'
 'Meadow Vista' 'Penn Valley' 'San Rafael' 'Herald' 'Castroville' 'Camino'
 'The Sea Ranch' 'Ben Lomond' 'Moss Landing' 'Aromas' 'Elverta' 'Soledad'
 'Yuba City' 'Dos Palos' 'Salida' 'Lucerne' 'Antelope' 'Rio Linda'
 'Benicia' 'Lower Lake' 'Winters' 'Oakdale' 'Turlock' 'Belmont'
 'Boulder Creek' 'Carmel' 'Mountain View' 'Royal Oaks' 'Foresthill'
 'Mendota' 'Keyes' 'Firebaugh' 'Monte Rio' 'Campbell' 'Larkspur' 'Nicasio'
 'Bodega Bay' 'Brentwood' 'San Gregorio' 'El Sobrante' 'Travis Afb'
 'Newman' 'Kelseyville' 'Carmel Valley' 'Meridian' 'Capitola' 'Lakeport'
 'Rumsey' 'Middletown' 'Georgetown' 'Biggs' 'Waterford' 'Nicolaus'
 'Gonzales' 'Greenbrae' 'Patterson' 'Rio Vista' 'Dunnigan' 'Copperopolis'
 'Alta' 'Willows' 'Marysville' 'Winton' 'Hilmar' 'Ukiah' 'Penngrove'
 'Clarksburg' 'Esparto' 'McClellan' 'Garden Valley' 'Oroville' 'Pacifica'
 'Los Banos' 'La Grange' 'Arbuckle' 'San Juan Bautista' 'Geyserville'
 'Jenner' 'Stanford' 'Oregon House' 'San Andreas' 'Dobbins' 'Brooks'
 'Sloughhouse' 'Pollock Pines' 'Hopland' 'Discovery Bay' 'Ceres'
 'Bay Point' 'Rescue' 'Mcclellan' 'Little River' 'Watsonville'
 'Emerald Hills' 'Diamond Springs' 'Felton' 'Cool' 'Pine Grove'
 'Upper Lake' 'Clearlake Oaks' 'Woodside' 'Atwater' 'Sutter Creek'
 'Lockeford' 'Coyote' 'Pescadero' 'La Honda' 'Pioneer' 'Lotus' 'Gustine'
 'Ballico' 'Cloverdale' 'Fairfax' 'Plymouth' 'Port Costa' 'Smartsville'
 'Saint Helena' 'Mount Hamilton' 'North San Juan' 'Courtland'
 'Monte Sereno' 'Applegate' 'Freedom' 'Mountain Ranch' 'Merced'
 'Clearlake' 'Graton' 'Pacheco' 'Maxwell' 'Kentfield' 'Stevinson'
 'Somerset' 'Capay' 'Hughson' 'Yorkville' 'Clayton' 'Crows Landing'
 'Belvedere Tiburon' 'Farmington' 'Rough and Ready' 'Zamora' 'Gualala'
 'Marina' 'Emigrant Gap' 'Rough And Ready' 'Point Reyes Station'
 'Southeast Marin' 'Soda Springs' 'Moss Beach' 'Vernalis' 'Redwood Valley'
 'Pebble Beach' 'Williams' 'Dutch Flat' 'Paicines' 'Oakley'
 'Browns Valley' 'Sutter' 'Gold River' 'Downieville' 'Fort Bragg'
 'Birds Landing' 'Fiddletown' 'Annapolis' 'Rancho Murieta' 'Big Sur'
 'Muir Beach' 'Norden' 'Sierra City' 'Livingston' 'Jamestown' 'Gridley'
 'Pleasant Grove' 'Davenport' 'Bodega' 'Sheridan' 'Alameda' 'Gold Run'
 'Olivehurst' 'Denair' 'Colusa' 'Marshall' 'Valley Ford' 'Volcano'
 'Kenwood' 'Potter Valley' 'Comptche' 'Cazadero' 'Camptonville'
 'Wheatland' 'Challenge' 'Pilot Hill' 'Chualar' 'Grizzly Flats'
 'Stonyford' 'Mendocino' 'Princeton' 'Woodbridge' 'Butte City' 'Bolinas'
 'Madison' 'Tomales' 'Glenhaven' 'Palermo' 'Woodacre' 'Montara'
 'Inverness' 'Greenwood' 'Glenn' 'Albion' 'Hickman' 'Atherton' 'Albany'
 'Dillon Beach' 'East Palo Alto' 'Knights Landing' 'West Point' 'Cobb'
 'El Macero' 'Guinda' 'West Contra Costa' 'Hillsborough' 'San Anselmo'
 'Diablo' 'Foster City' 'Berry Creek' 'Santa Barbara' 'Ventura'
 'Simi Valley' 'Sylmar' 'North Hollywood' 'Los Angeles'
 'La Canada Flintridge' 'South El Monte' 'La Puente' 'Orange' 'Santa Ana'
 'Pomona' 'Riverside' 'Vista' 'Temecula' 'Running Springs' 'Newhall'
 'Inglewood' 'Downey' 'San Diego' 'Escondido' 'Mentone' 'Ontario'
 'Fontana' 'Colton' 'Redlands' 'Moreno Valley' 'Spring Valley'
 'Sun Valley' 'Cerritos' 'Anaheim' 'Tustin' 'Highland' 'Santee'
 'Buena Park' 'Sherman Oaks' 'Torrance' 'Long Beach' 'Montebello'
 'Norwalk' 'Pacoima' 'Pasadena' 'La Jolla' 'Oxnard' 'Chino' 'Irvine'
 'Diamond Bar' 'Hacienda Heights' 'El Monte' 'Hemet' 'Calabasas'
 'Glendale' 'Compton' 'Lynwood' 'Van Nuys' 'Mira Loma' 'Encinitas' 'Pala'
 'Valencia' 'Corona' 'Carlsbad' 'Commerce' 'Carson' 'Valley Village'
 'Gardena' 'Whittier' 'Oceanside' 'Perris' 'Hesperia' 'Lawndale'
 'Fullerton' 'Lake Elsinore' 'Santa Fe Springs' 'Canyon Country'
 'El Cajon' 'Stevenson Ranch' 'Valley Center' 'Culver City' 'San Pedro'
 'San Bernardino' 'National City' 'Camarillo' 'San Ysidro' 'Covina'
 'Bloomington' 'Baldwin Park' 'Rialto' 'Alhambra' 'Rosemead' 'Brea'
 'Porter Ranch' 'Westminster' 'Acton' 'Newbury Park' 'Walnut'
 'Mission Viejo' 'Altadena' 'Forest Falls' 'Rowland Heights' 'Arcadia'
 'Menifee' 'Chula Vista' 'Landers' 'Moorpark' 'Santa Monica' 'Murrieta'
 'La Crescenta' 'Encino' 'Topanga' 'March Air Reserve Base' 'Harbor City'
 'Upland' 'Yorba Linda' 'Solana Beach' 'Alpine' 'Montclair'
 'Santa Clarita' 'Santa Ysabel' 'Seal Beach' 'La Mesa' 'Big Bear City'
 'Westlake Village' 'Tarzana' 'South Pasadena' 'Grand Terrace'
 'Huntington Beach' 'Mission Hills' 'San Fernando' 'Hawthorne'
 'Bellflower' 'Lake Arrowhead' 'Ramona' 'Studio City' 'Beaumont'
 'Garden Grove' 'Rancho Cucamonga' 'Julian' 'Glendora' 'San Gabriel'
 'Paramount' 'City Of Industry' 'San Marcos' 'Azusa' 'San Dimas'
 'South Gate' 'Huntington Park' 'Oak Park' 'Marina Del Rey' 'North Hills'
 'Cardiff By the Sea' 'Woodland Hills' 'Monterey Park' 'Pacific Palisades'
 'Fallbrook' 'Calimesa' 'Victorville' 'Placentia' 'Bonsall' 'San Clemente'
 'Fountain Valley' 'Granada Hills' 'West Covina' 'Del Mar'
 'Thousand Palms' 'Banning' 'Pico Rivera' 'Monrovia' 'Costa Mesa'
 'San Juan Capistrano' 'San Jacinto' 'Homeland' 'La Mirada' 'Bell Gardens'
 'Norco' 'Artesia' 'Littlerock' 'Chatsworth' 'Laguna Hills' 'Agoura Hills'
 'Pauma Valley' 'Desert Hot Springs' 'Indio' 'Duarte' 'Stanton' 'Ojai'
 'Winchester' 'Castaic' 'Silverado' 'Rancho Santa Fe' 'Lakeside'
 'Coronado' 'Potrero' 'Ladera Ranch' 'Fillmore' 'Marina del Rey'
 'Palm Springs' 'Foothill Ranch' 'Descanso' 'Pine Valley' 'Cabazon'
 'North Palm Springs' 'Camp Pendleton' 'Toluca Lake' 'Palmdale'
 'Loma Linda' 'Carpinteria' 'Cathedral City' 'La Verne' 'Valyermo'
 'Aguanga' 'Bonita' 'Newport Beach' 'Wildomar' 'Lemon Grove' 'Malibu'
 'Lucerne Valley' 'Phelan' 'Laguna Niguel' 'Nuevo' 'Trabuco Canyon'
 'Palm Desert' 'View Park' 'Lakewood' 'Boulevard' 'Mountain Center'
 'Goleta' 'Idyllwild' 'Twin Peaks' 'Santa Paula' 'Rimforest' 'La Palma'
 'Winnetka' 'Vernon' 'La Habra' 'Signal Hill' 'Claremont' 'Sun City'
 'Montrose' 'Wrightwood' 'Sunland' 'Yucaipa' 'Chino Hills' 'Jamul'
 'El Segundo' 'Crestline' 'Rolling Hills Estates' 'Tujunga'
 'Thousand Oaks' 'Pinon Hills' 'Llano' 'Campo' 'Capistrano Beach' 'Anza'
 'Rancho Dominguez' 'Canoga Park' 'Los Alamitos' 'Oak Hills' 'Venice'
 'Lake Forest' 'Cedar Glen' 'Laguna Beach' 'Aliso Viejo'
 'Santa Rosa Valley' 'Angelus Oaks' 'Joshua Tree' 'Somis' 'Midway City'
 'San Marino' 'Playa del Rey' 'Temple City' 'Ranchita' 'Sugarloaf'
 'Maywood' 'La Habra Heights' 'Corona del Mar' 'Oak View' 'Apple Valley'
 'Redondo Beach' 'Hawaiian Gardens' 'Yucca Valley' 'Whitewater' 'Blue Jay'
 'Skyforest' 'Dulzura' 'Irwindale' 'Palos Verdes Peninsula'
 'Morongo Valley' 'Windsor Hills' 'Point Mugu Nawc' 'Universal City'
 'Poway' 'Bell' 'Bermuda Dunes' 'West Hollywood' 'Lompoc'
 'Borrego Springs' 'Warner Springs' 'Mt Baldy' 'Cedarpines Park' 'Tecate'
 'Newport Coast' 'Northridge' 'Cherry Valley' 'Rancho Santa Margarita'
 'Rancho Mirage' 'Pearblossom' 'Big Bear Lake' 'Panorama City'
 'Summerland' 'Playa Del Rey' 'Bell Canyon' 'Arleta' 'Cypress'
 'Dana Point' 'Beverly Hills' 'Rancho Palos Verdes' 'Port Hueneme'
 'Reseda' 'La Quinta' 'Adelanto' 'Piru' 'Hidden Hills' 'Lytle Creek'
 'West Hills' 'Sunset Beach' 'Imperial Beach']

County:
['Montgomery' 'Franklin' 'Clermont' 'Licking' 'Fairfield' 'Warren'
 'Clinton' 'Cuyahoga' 'Hancock' 'Greene' 'Miami' 'Delaware' 'Summit'
 'Richland' 'Medina' 'Crawford' 'Pickaway' 'Adams' 'Putnam' 'Lorain'
 'Wayne' 'Muskingum' 'Wood' 'Madison' 'Guernsey' 'Brown' 'Ross' 'Allen'
 'Clark' 'Fayette' 'Gallia' 'Erie' 'Solano' 'Alameda' 'Contra Costa'
 'Santa Clara' 'San Francisco' 'Sonoma' 'Sacramento' 'San Mateo' 'Yolo'
 'Placer' 'Nevada' 'El Dorado' 'Marin' 'San Joaquin' 'Mendocino' 'Lake'
 'Napa' 'Santa Cruz' 'Monterey' 'Stanislaus' 'Calaveras' 'Amador'
 'San Benito' 'Merced' 'Sutter' 'Fresno' 'Butte' 'Colusa' 'Yuba' 'Glenn'
 'Sierra' 'Tuolumne' 'Santa Barbara' 'Ventura' 'Los Angeles' 'Orange'
 'Riverside' 'San Diego' 'San Bernardino']

State:
['OH' 'WV' 'CA']

Airport_Code:
['KFFO' 'KCMH' 'KI69' 'KDAY' 'KMGY' 'KTZR' 'KOSU' 'KLCK' 'KILN' 'KLHQ'
 'KBKL' 'KFDY' 'KVES' 'KDLZ' 'KAKR' 'KMFD' 'KCLE' 'KVTA' 'KBJJ' 'KCRW'
 'KLPR' 'KZZV' 'KTDZ' 'KHAO' 'K3I2' 'KAOH' 'KSGH' 'KPCW' 'KAPC' 'KHWD'
 'KCCR' 'KNUQ' 'KRHV' 'KLVK' 'KSJC' 'KSFO' 'KO69' 'KSAC' 'KMCC' 'KOAK'
 'KE16' 'KSTS' 'KPAO' 'KEDU' 'KHAF' 'KSQL' 'KMHR' 'KGOO' 'KVCB' 'KSUU'
 'KSMF' 'KLHM' 'KPVF' 'KDVO' 'KSCK' 'KUKI' 'KWVI' 'KSNS' 'KMRY' 'KAUN'
 'KMOD' 'KO22' 'KCVH' 'KMER' 'KMYV' 'KMCE' 'KMAE' 'KOVE' 'KBLU' 'KCIC'
 'KBAB' nan 'KTRK' 'KSBA' 'KOXR' 'K3A6' 'KWHP' 'KBUR' 'KCQT' 'KMWS' 'KEMT'
 'KSNA' 'KPOC' 'KRAL' 'KCRQ' 'KF70' 'KSBD' 'KHHR' 'KMYF' 'KNKX' 'KONT'
 'KRIV' 'KSEE' 'KTOA' 'KFUL' 'KVNY' 'KSMO' 'KLGB' 'KCNO' 'KSAN' 'KBUO'
 'KAJO' 'KOKB' 'KVCV' 'KLAX' 'KRNM' 'KNRS' 'KCMA' 'KSDM' 'KSLI' 'KPMD'
 'KNXP' 'KL35' 'KNZY' 'KNFG' 'KNXF' 'KPSP' 'KTRM' 'KCZZ' 'KGXA' 'KNSI'
 'KLPC']

Weather_Timestamp:
['2016-02-08 05:58:00' '2016-02-08 05:51:00' '2016-02-08 06:56:00' ...
 '2016-04-05 14:51:00' '2016-04-05 15:51:00' '2016-04-05 15:45:00']

Temperature(F):
[ 36.9  37.9  36.   35.1  34.   33.3  37.4  35.6  33.8  37.   39.9  39.2
  34.2  33.1  23.   22.8  26.6  21.   19.9  25.   26.1  24.8  21.9  21.2
  22.5  32.   27.   16.2  15.8  15.4  14.   15.1  16.   17.6  17.1   7.
   6.1   5.   12.    9.    7.5  18.   10.9  13.6  10.4  18.5  21.6  19.
  25.5  10.    8.1  12.9  24.1  30.9  33.6  32.9  32.2  30.   31.1  32.4
  30.4  28.4  28.   30.2  30.7   3.9  25.9  28.9  39.   35.4  34.9  43.5
  41.   42.8  43.   47.7  48.   49.6  53.8  57.   59.4  46.4  65.1  29.5
  27.9  32.5  48.7  46.9  47.5  31.8  38.3  48.4  54.   53.1  50.   44.6
  42.1  40.6  49.   44.1  46.   45.   52.   33.4  34.3  63.1  62.8  54.1
  52.5  48.9  46.6  54.3  53.6  55.9  48.2  29.8  25.2  30.6  31.6  60.1
  57.9  62.1  59.   62.4  58.8  51.1  50.5  55.4  55.2  55.   56.7  61.2
  66.   70.2  68.   71.6  71.1  69.1  66.9  63.   61.   64.   70.   73.
  69.8  57.2  59.2  60.8  59.9  58.5  57.6  58.6  56.5  45.5  45.9  51.8
  57.4  65.8  64.9  67.8  64.4  60.4  62.6  37.8  46.8  39.7  55.8  75.
  82.9  75.9  75.2  80.6  86.   73.9  82.   84.   88.   82.4  84.2  87.8
  77.   89.6  90.   87.1  91.4  91.9  93.2  93.9  79.   98.1  96.8  97.
  78.8  99.   95.   98.6  80.1  81.   78.1  72.   73.4  66.2  85.3  89.1
  91.   84.9  71.4  96.1 100.4  93.   96.6  89.2 100.  104.  100.9 102.2
 102.  102.9  73.6  77.5  61.7  76.8  57.7  68.2  72.5  86.7 103.6 102.6
  77.4 106.   81.9  79.3  95.7  60.3  99.5  81.1  88.7  87.6  80.8  47.1
  41.4  56.1  53.2  35.8  43.7  36.1  50.4  39.4  40.3  54.7  41.5  58.1
  36.3  52.9  41.9  43.2  78.3  62.2  64.2  50.9  68.4  64.6  66.7  66.4
  68.7  56.8  59.5  74.3  55.6  44.4  51.6  48.6  61.5  69.3  64.8  86.2
  54.5  83.5  75.4  47.3  54.9  65.5  77.9  59.7  61.9  68.9  81.3  76.3
  85.6  82.8  65.3  95.4  86.9  88.3  70.5  69.6  73.8  63.9  74.8  63.5
  58.3  90.9  67.1  72.3  52.2  61.3  49.8  84.4  79.5  56.3  80.2  79.7
  72.1  63.3  79.2  76.5  68.5  84.7  79.9  92.7  72.7  69.4  87.   83.7
  88.5  96.   94.   92.1  98.4 105.8  85.   92.5  90.7  90.1  83.   70.3
  85.1  80.   76.6  93.4  89.   97.7  74.   74.1  78.   75.7  92.   91.6
  94.1  74.7  66.6  67.6  76.   85.5 109.   65.   92.8 106.3  77.7  94.3
 101.  105.1  74.5 113.   95.9 107.1  87.3  95.5  98.8  78.6 100.6  95.2
  94.6  71.8 101.3 102.4 101.8  97.3  91.8  86.5  83.8  70.7  81.7  94.5
  62.   60.   71.   91.2  82.6  70.9  72.9  77.2  81.5  75.6  67.   58.
  76.1  90.3  73.2  78.4 111.   99.1  96.3 100.8  84.6 109.9  96.4 103.
 105.  106.7 109.4 111.2 107.  101.7 108.  108.5  92.3  99.9  88.2  98.
  99.3  86.4  83.3 103.1 103.3  56.   53.   51.3  53.4  49.5  38.7  47.
  44.   51.   49.3  51.4  47.8  43.3  52.7  49.1  45.3  35.2  36.5  37.2
  34.5  44.2  42.4  43.9  42.3  50.7  52.3  63.7  60.6  44.8  46.2  42.
  39.6  38.    3.2  29.7  40.5  40.   71.2  67.5  89.8  65.7  69.   80.4
  83.1  67.3  40.1  50.2  45.1  41.2  97.9  97.2 104.7  82.2  94.8  90.5
  89.4  85.8 107.6 102.7 114.1  88.9  97.5  98.2  93.6  42.6]

Wind_Chill(F):
[ 42.5  33.3  31.   35.5  33.8  30.7  31.1  32.1  30.3  29.6  28.6  32.4
  30.9  34.4  29.   32.9  34.5  35.9  31.6  31.2  26.1  25.5  11.7  11.5
  18.2  10.6  12.4   6.7  15.5  10.1  15.   16.1   9.8   8.3   8.9  10.4
  22.5   9.5  13.5   4.7   2.7   1.   -1.4   4.2   6.1   1.7   4.4   5.
   3.4   3.    8.6   7.3   2.9   0.5   1.2  -5.7  -0.3  -6.8  -2.1  -1.6
  -1.1   1.5  -0.2   0.2   7.7   2.2   8.7   7.5   9.3  13.   14.6  11.4
  14.3  12.9  11.1   1.6   3.2  -4.5  -8.4  -8.3  -1.8  -3.4   0.4  13.9
  14.5  13.6  15.8  17.   17.9  17.6  17.1  19.4  23.   26.4  24.8  23.5
  27.7  30.6  28.   25.8  23.6  22.2  25.6  21.1  24.2  22.8  28.7  23.2
  24.9  25.4  24.1  27.9  25.3  26.9  21.2  27.5  21.7  20.8  22.4  26.5
  25.2  24.5  23.4  18.   23.9  32.2  28.5   6.9   6.3  19.5  12.5  33.4
  31.5  28.2  28.9  29.3  30.8  28.4  27.1  29.7  37.1  34.7  37.   39.2
  24.   28.1  30.1  26.6  34.3  38.   38.8  21.9  27.   26.7  39.7  33.9
  27.3  29.8  34.9  34.8  32.5  45.   37.5  36.8  33.1  40.6  37.9  25.9
  39.   20.2  17.8  24.3  21.6  24.4  19.2  37.7  27.4  24.7  30.   32.8
  32.   33.6  37.2  41.4  41.   42.6  30.4  14.8  19.3  20.9  20.   26.
  27.2  28.3  23.3  36.6  42.4  66.   40.7  40.3  38.9  40.8  40.1  39.5
  41.3  37.6  41.1  44.3  42.2  43.1  41.8  43.9  40.2  31.7  38.4  45.2
  40.4  35.7  41.9  43.5  41.5  44.8  39.4  35.   36.7  39.3  37.8  33.5
  36.4  35.8  29.2  35.1  38.1  16.7  39.9  18.1  41.2  42.9  33.   38.6
  31.4  20.7  19.8  20.5  34.2  35.2  32.7  39.1  32.3  38.2  19.1  30.5
  39.8  31.8  29.9  28.8  24.6  37.4  35.3  38.5  36.9  31.9  38.7  36.2
  87.   96.   94.   85.   83.   79.   80.   90.   89.   82.   74.   70.
  63.   78.   84.   92.   75.   73.   68.   76.   81.   88.   77.   64.
  65.   97.   72.  101.   91.   61.   62.   60.   71.   86.   67.   58.
  93.   95.   99.  102.  103.  105.  106.  107.   98.  100.   52.   56.
  53.   48.   36.   44.   46.   47.   57.   50.   51.   54.   59.   43.

In [ ]:
df.duplicated().sum()

np.int64(17)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in),start_year,start_month,start_day,start_hour
count,99983.000000,99983,99983,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000,99983.000000
mean,2.448096,2016-09-13 05:03:13.054189312,2016-09-13 05:45:45.186341376,35.630534,-119.322868,0.011346,66.631563,42.774186,59.834782,29.961152,9.350996,7.771708,0.001900,2016.093386,7.783783,15.949281,13.503466
min,1.000000,2016-02-08 05:46:00,2016-02-08 06:37:59,32.542587,-123.813927,0.000000,3.200000,-8.400000,4.000000,2.980000,0.100000,0.000000,0.000000,2016.000000,1.000000,1.000000,0.000000
25%,2.000000,2016-07-19 10:50:35,2016-07-19 11:32:00,33.957791,-121.828674,0.000000,57.900000,42.500000,44.000000,29.890000,10.000000,5.800000,0.000000,2016.000000,6.000000,8.000000,10.000000
50%,2.000000,2016-09-18 18:01:09,2016-09-18 18:32:13,34.168777,-118.384232,0.000000,66.000000,42.500000,62.000000,29.970000,10.000000,6.900000,0.000000,2016.000000,8.000000,16.000000,14.000000
75%,3.000000,2016-11-20 00:36:28,2016-11-20 01:06:53,37.776788,-117.916023,0.010000,75.000000,42.500000,78.000000,30.060000,10.000000,9.200000,0.000000,2016.000000,10.000000,23.000000,18.000000
max,4.000000,2017-01-26 20:07:03,2017-01-26 20:52:00,41.428753,-81.550728,51.130000,114.100000,107.000000,100.000000,33.040000,80.000000,241.700000,0.550000,2017.000000,12.000000,31.000000,23.000000
std,0.499929,NaN,NaN,2.101262,3.663751,0.262266,12.602592,4.332841,22.970008,0.273866,1.870225,3.783755,0.015566,0.290974,3.269070,8.766992,5.778622

In [ ]:
import plotly.express as px
fig = px.box(df, y="Distance(mi)", title="Boxplot of Distance (mi)")
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, y="Wind_Speed(mph)", title="Boxplot of Wind_Speed(mph)")
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, y="Visibility(mi)", title="Boxplot of Visibility(mi)")
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, y="Humidity(%)", title="Humidity(%)")
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, y="Wind_Chill(F)", title="Boxplot of Wind_Chill(F)")
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, y="Temperature(F)", title="Boxplot of Temperature(F)")
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, y="Precipitation(in)", title="Boxplot of Precipitation(in)")
fig.show()

In [ ]:
import plotly.express as px
fig = px.box(df, y="Pressure(in)", title="Pressure(in)")
fig.show()

In [ ]:
bool_cols = df.select_dtypes(include='bool')
summary = pd.DataFrame({
    "True_Count": bool_cols.sum(),
    "False_Count": bool_cols.shape[0] - bool_cols.sum()
})

summary

                 True_Count  False_Count
Amenity                 784        99199
Bump                     48        99935
Crossing               6487        93496
Give_Way                166        99817
Junction              10434        89549
No_Exit                  54        99929
Railway                1262        98721
Roundabout                5        99978
Station                3167        96816
Stop                   3324        96659
Traffic_Calming          78        99905
Traffic_Signal        10698        89285
Turning_Loop              0        99983